logging:
  file: logs/monitoring.log 
  
eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true      

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000

ribbon:
  ReadTimeout: 20000
  ConnectTimeout: 20000

spring:
  rabbitmq:
    host: localhost
    # username: cloud
    # password: cloud

---
# For deployment in Docker containers
spring:
  profiles: docker

  rabbitmq:
    host: rabbitmq

logging:
  file: /logs/monitoring.log 
  
eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://registry:8761/eureka/
  